// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { formatDuration } from "./formatDuration.js";

interface Track {
    added: string
    album: string
    albumartist: string
    artist: string
    date: string
    disc: number
    duration: number
    file: string
    genre: string
    last_modified: string
    time: number
    title: string
    track: number
    format: {
        bits: string
        channels: number
        original_value: string
        sample_rate: number
        sample_rate_short: {
            unit: string
            value: number
        }
    }
}

declare namespace Track {
    export {
        formatDuration,
    }
}

export {
    Track,
}
