// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { formatDuration } from "./formatDuration.js";

export const Track = {
    formatDuration,
}
