// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { $current } from "./$current.js";
import { fetch } from "./fetch.js";
import { sync } from "./sync.js";

export const Status = {
    $current,
    fetch,
    sync,
}
