// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { $current } from "./$current.js";
import { fetch } from "./fetch.js";
import { sync } from "./sync.js";

interface Status {
    consume: boolean
    duration?: number
    elapsed?: number
    file?: string
    lastloadedplaylist: ""
    mixrampdb: number
    nextsong: number
    nextsongid: number
    partition: string
    playlist: number
    playlistlength: number
    random: boolean
    repeat: boolean
    single: boolean
    song: number
    songid: number
    state: "stop" | "play" | "pause"
    volume: number
}

declare namespace Status {
    export {
        $current,
        fetch,
        sync,
    }
}

export {
    Status,
}
