// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { render } from "./render.js";

declare namespace Statusbar {
    export {
        render,
    }
}

export {
    Statusbar,
}
