// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

interface Playlist {
    files: string[]
    title: string
}

declare namespace Playlist {
    export {

    }
}

export {
    Playlist,
}
