// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { $all } from "./$all.js";
import { fetch } from "./fetch.js";

export const Playlists = {
    $all,
    fetch,
}
