// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { $all } from "./$all.js";
import { fetch } from "./fetch.js";

declare namespace Playlists {
    export {
        $all,
        fetch,
    }
}

export {
    Playlists,
}
