// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { input } from "./input.js";
import { render } from "./render.js";

export const Cmdline = {
    input,
    render,
}
